{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zammad-wrapper.labels" . | nindent 4 }}
spec:
  encryptedData:
    postgresql-password: {{ .Values.secrets.encryptedPostgresPassword | quote }}
    postgresql-postgres-password: {{ .Values.secrets.encryptedPostgresAdminPassword | quote }}
    secret-key-base: {{ .Values.secrets.encryptedSecretKeyBase | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
