apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windeployment-files
  namespace: windeployment
spec:
  accessModes:
    - ReadWriteOnce
  # StorageClass "hdd" → /mnt/hdd/k8s-storage auf worker-0 (7,3 TB sda)
  storageClassName: hdd
  resources:
    requests:
      storage: 500Gi
