apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windeployment-files
  namespace: windeployment
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
