apiVersion: v1
kind: Service
metadata:
  name: windeployment-http
  namespace: windeployment
  labels:
    app: windeployment-http
spec:
  type: NodePort
  selector:
    app: windeployment-http
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30090
