{{- if .Values.grafana.tokenSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.grafana.tokenSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "le-homeserver.labels" . | nindent 4 }}
spec:
  encryptedData:
    token: {{ .Values.grafana.tokenSecret.encryptedToken | quote }}
  template:
    metadata:
      name: {{ .Values.grafana.tokenSecret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
