apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBzDWaAtdZ2yA4EsLHPkSnrkshZ2UXXZ7iIccKh8VLTdMoUkKyNq86KxujLuTTE6BCeJVmf7mZJ0YkXhinWfiMshu10KanSDL9PnRujyBlOSwKiGj46hE6alfgeFruHqC5hhIulwiIcnUG4I9L+OEa/nnuWUjVqj1YwRoe2qBW7Yv4mwQCVn7j0ZUGerH2koCDhjfavxl/ViO2G7tbkY+eO1TswrZJw45400yadFhJvGa2bsXPXDSFxOZbsKkKVUhiiCVXvFje0OQtsl/ZVYbEsGcz9/s00a6RNtQEhGFrpB4JOe8r5yz7x/0TmzPubVK4rmF9157JtUo2S4K1Oog/YwHaZm09ljloHqky0DyTPRhhhbFrCrm+iQlNbG2mjMxXJUZy815cMk8K9A6VPTVdhBSs9MusvmegZc39c6B8pMosJyd1pdOKLnu2zLawLCxjp66JGpIiwHOdyu0AAxQYpr6pjVgPvYFQAft+wkZWvEbB9aAHHtn7ftnPXk3eRqYA6p9DjYhMhT3HhSYNhmxqZ2ZEFFwCDTD1Ot0jioIRGRv2E4ULdbThk+0hoILU9fP2xhJDy/iSQO93WLHGjYhYlNknuYFUWpokWlPj9PhqyEufI+yCpvAzjvXchbKRVtHaTw1RNS50XmXsG6ZoFbLZ7zFgNSZV4aU2c5YxMKFUI6NSN6WZ1H668KGynfvl63Q+x1GsnmAPJ0G4xIe/BNUjnX2lQDfC1fsEn+dhZn9eEJXTrJbqWTtPV/pr8FNZYQqVklpv5si+uJnQkkeHAE3WsfODkxvLRfDvahnqRPjpaL/Zk48TESR3b9Jujyhy+f6n3yQWxAg2QvwL6Qy5Lqk2vwqzM1ltXqnxBHSEvDk67KA==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
    type: Opaque
